// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLH90BrK4BQ9gfd11F_v7Ka6QSNi7K4w',
    appId: '1:58083406705:web:87f849a22983ef0ca83cd0',
    messagingSenderId: '58083406705',
    projectId: 'authentication-46903',
    authDomain: 'authentication-46903.firebaseapp.com',
    storageBucket: 'authentication-46903.appspot.com',
    measurementId: 'G-JCKVJ62MTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Wu6ldZA2nqTbeeRhQ5u1C4_9EKbQaVY',
    appId: '1:58083406705:android:76b2e1250e7d0dd2a83cd0',
    messagingSenderId: '58083406705',
    projectId: 'authentication-46903',
    storageBucket: 'authentication-46903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAeI7-P47w594fGBTax7qJ_Lb5vU-ZOU',
    appId: '1:58083406705:ios:301417e3781d4744a83cd0',
    messagingSenderId: '58083406705',
    projectId: 'authentication-46903',
    storageBucket: 'authentication-46903.appspot.com',
    iosBundleId: 'com.example.fireBaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPLH90BrK4BQ9gfd11F_v7Ka6QSNi7K4w',
    appId: '1:58083406705:web:459eea9fe9441619a83cd0',
    messagingSenderId: '58083406705',
    projectId: 'authentication-46903',
    authDomain: 'authentication-46903.firebaseapp.com',
    storageBucket: 'authentication-46903.appspot.com',
    measurementId: 'G-DZK5DB84T2',
  );
}
